import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/NavBar";
import Context from "@/Context/Context.jsx";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ShopHive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Context>
          <Toaster position="bottom-center" toastOptions={{ duration: 2000 }} />
          <NavBar />
          {children}
        </Context>
      </body>
    </html>
  );
}
